site_name: Decalemaxithu's wiki

repo_name : Decalemaxithu's wiki
repo_url : https://github.com/camlthx/camlthx.github.io

theme:
  name: "material"
  language: "zh"
  features:
    header.tooltips
    header.autohide
    navigation.footer
    navigation.top
    navigation.tabs

  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon :
    repo : fontawesome/brands/git-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16



nav:
  - 首页 : index.md
  - OI相关:
    - 简介 : OI_related/OI.md
    - 题解 :
      - SLOJ P2582 层流 : OI_related/SLOJ_P2582.md
      - SLOJ P2853 Graph : OI_related/SLOJ_P2583.md
      - SLOJ P2601 路径的交 : OI_related/SLOJ_P2601.md
      - SLOJ P2604 与或 : OI_related/SLOJ_P2604.md
      - SLOJ P2623 three : OI_related/SLOJ_P2623.md
      - SLOJ P3045 食堂 : OI_related/SLOJ_P3045.md
      - BZOJ 3333 排队计划 : OI_related/bzoj3333.md
      - BZOJ 4977 跳伞求生 : OI_related/bzoj4977.md
      - Luogu P1712 [NOI2016]区间 : OI_related/luoguP1712.md
      - Luogu P2680 [NOIP2015提高]运输计划 : OI_related/luoguP2680.md
      - Luogu P2839 middle : OI_related/luoguP2839.md
      - Luogu P2894 [USACO08FEB]Hotel G : OI_related/luoguP2894.md
      - Luogu P3225 矿场搭建 : OI_related/luoguP3225.md
      - Luogu P3313 [SDOI2014]旅行 : OI_related/luoguP3313.md
      - Luogu P3596 [POI2014]KAR-Cards : OI_related/luoguP3569.md
      - Luogu P3852 [POI2015]Kinoman : OI_related/luoguP3852.md
      - Luogu P4041 [AHOI2014]奇怪的计算器 : OI_related/luoguP4041.md
      - Luogu P4180 严格次小生成树 : OI_related/luoguP4180.md
      - Luogu P4315 月下“毛景树” : OI_related/luoguP4315.md
      - CF400D Dima and Bacteria : OI_related/CF400D_Dima_and_Bacteria.md
      - CF567E President and Roads : OI_related/CF567E_President_and_Roads.md

      - 测试模拟 :
        - 10.25 CSP-J模拟 : OI_related/10.25_practice.md
        - 10.22 CSP-J模拟 : OI_related/10.22_practice.md
        - 8.10 夏令营测试 : OI_related/8.10_summer_camp.md
    - 奇技淫巧 :
        - 多叉树转二叉树 : OI_related/tree_transform.md
        - 龟速乘 : OI_related/quick_plus.md
    - 学习笔记 :
        - 简单数论 : OI_related/simple_number_theory.md
        - dfs 序 : OI_related/dfs_order.md
        - 2.6-2.10 数据结构与dp专练 : OI_related/2.6practice.md
    - 杂项 :
        - 警 示 自 己 : OI_related/oi_warning.md
  - markdown :
      - markdown简介 : markdown/introdution.md
      - markdown基本语法 : markdown/basic_grammar.md
  - cubing :
    - 简介 : cubing/Cubing.md
  - 文章 :
      - 西川实验随笔 : compositions/xcsy.md
  - 杂物堆 :
      - 相关链接 : link.md
  - 关于 :
      - 关于我 : about.md
      - 更新日记 : upd.md


plugins:
  - search:
      jieba_dict: dict.txt

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/camlthx
      name: Camlthx on Github
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/404422165
      name: account on bilibili
    - icon: fontawesome/solid/cubes-stacked
      link: https://www.worldcubeassociation.org/persons/2018MOTI02
      name: 2018MOTI02
    - icon: fontawesome/solid/paper-plane
      link: mailto:<decalemaxithu@qq.com>

copyright: Copyright &copy; 2023 Mo Tianhao


markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
