site_name: Decalemaxithu's wiki

theme:
  name: "material"
  language: "zh"
  features:
    header.tooltips
    header.autohide
    navigation.footer

  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode



nav:
  - 首页 : index.md
  - OI相关:
    - 简介 : OI_related\OI.md
    - 题解 :
      - SLOJ :
        - P3045食堂 : OI_related\SLOJ_P3045.md
      - Luogu :
        - P3225矿场搭建 : OI_related\luoguP3225.md
      - Codeforce :
        - CF400D Dima and Bacteria : OI_related\CF400D_Dima_and_Bacteria.md
        - CF567E President and Roads : OI_related\CF567E_President_and_Roads.md
      - 测试模拟 :
        - 10.25 CSP-J模拟 : OI_related\10.25_practice.md
        - 10.22 CSP-J模拟 : OI_related\10.22_practice.md
        - 8.10 夏令营测试 : OI_related\8.10_summer_camp.md
    - 奇技淫巧 :
        - 多叉树转二叉树 : OI_related\tree_transform.md
        - 龟速乘 : OI_related\quick_plus.md
    - 学习笔记 :
        - 简单数论 : OI_related/simple_number_theory.md
        - dfs 序 : OI_related/dfs_order.md
    - 杂项 :
        - 警 示 自 己 : OI_related\oi_warning.md
  - cubing :
    - 简介 : cubing\Cubing.md
  - 文章 :
      - 西川实验随笔 : compositions\xcsy.md
  - 关于 : about.md

plugins:
  - search:
      jieba_dict: dict.txt

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/camlthx
      name: Camlthx on Github
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/404422165
      name: account on bilibili
    - icon: fontawesome/solid/cubes-stacked
      link: https://www.worldcubeassociation.org/persons/2018MOTI02
      name: 2018MOTI02
    - icon: fontawesome/solid/paper-plane
      link: mailto:<decalemaxithu@qq.com>
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
